<?php namespace App\Modules\epersonal\nominatifpenjagaanpkpppk\Models;
use Illuminate\Database\Eloquent\Model;


/**
* Nominatifpenjagaanpkpppk Model
* @var Nominatifpenjagaanpkpppk
* Generate from Custom Laravel 5.1 by Aa Gun. 
*
* Developed by Dinustek. 
* Please write log when you do some modification, don't change anything unless you know what you do
* Semarang, 2016
*/

class NominatifpenjagaanpkpppkModel extends Model {
	protected $guarded = array();
	
	protected $table = "tb_01";

	public static $rules = array(
    		'nama' => 'required',
		'gdp' => 'required',
		'gdb' => 'required',
		'tmlhr' => 'required',
		'tglhr' => 'required',
		'idjenkel' => 'required',
		'idagama' => 'required',
		'idstspeg' => 'required',
		'idjenkepeg' => 'required',
		'idjenkedudupeg' => 'required',
		'ket' => 'required',
		'tmtket' => 'required',
		'idstskawin' => 'required',
		'alm' => 'required',
		'almrt' => 'required',
		'almrw' => 'required',
		'almdesa' => 'required',
		'almkec' => 'required',
		'almkab' => 'required',
		'almprov' => 'required',
		'almkdpos' => 'required',
		'idlokkel' => 'required',
		'idlokkec' => 'required',
		'idlokkab' => 'required',
		'idlokpro' => 'required',
		'telp' => 'required',
		'hp' => 'required',
		'idgoldarah' => 'required',
		'nokarpeg' => 'required',
		'noaskes' => 'required',
		'notaspen' => 'required',
		'nokaris' => 'required',
		'nonpwp' => 'required',
		'noktp' => 'required',
		'nobapertarum' => 'required',
		'photo' => 'required',
		'userin' => 'required',
		'tmstamp' => 'required',
		'userup' => 'required',
		'tmstampup' => 'required',
		'password' => 'required',
		'lastlogin' => 'required',
		'nobkncpn' => 'required',
		'tgbkncpn' => 'required',
		'pejmencpn' => 'required',
		'noskcpn' => 'required',
		'tgskcpn' => 'required',
		'idgolrucpn' => 'required',
		'tmtcpn' => 'required',
		'mkthncpn' => 'required',
		'mkblncpn' => 'required',
		'tmttgscpn' => 'required',
		'nosttpdikcpn' => 'required',
		'tgsttpdikcpn' => 'required',
		'pejmenpns' => 'required',
		'noskpns' => 'required',
		'tgskpns' => 'required',
		'idgolrupns' => 'required',
		'tmtpns' => 'required',
		'idsumpahpns' => 'required',
		'nobknpkt' => 'required',
		'tgbknpkt' => 'required',
		'pejmenpkt' => 'required',
		'noskpkt' => 'required',
		'tgskpkt' => 'required',
		'idgolrupkt' => 'required',
		'tmtpkt' => 'required',
		'mkthnpkt' => 'required',
		'mkblnpkt' => 'required',
		'akpkt' => 'required',
		'pejmenkgb' => 'required',
		'nosuratkgb' => 'required',
		'tgsuratkgb' => 'required',
		'noskkgb' => 'required',
		'tgskkgb' => 'required',
		'idgolkgb' => 'required',
		'tmtkgb' => 'required',
		'mkgolthnkgb' => 'required',
		'mkgolblnkgb' => 'required',
		'kantorkgb' => 'required',
		'idsatker' => 'required',
		'idsekolah' => 'required',
		'kdunit' => 'required',
		'idskpd' => 'required',
		'tmpkdunit' => 'required',
		'tmpidskpd' => 'required',
		'tmtskpd' => 'required',
		'almloker' => 'required',
		'almlokertelp' => 'required',
		'sekolah' => 'required',
		'pejmenjbt' => 'required',
		'noskjbt' => 'required',
		'tgskjbt' => 'required',
		'idjenjab' => 'required',
		'idesljbt' => 'required',
		'tmtesljbt' => 'required',
		'stsesl' => 'required',
		'idkeljab' => 'required',
		'idjabjbt' => 'required',
		'idjabfung' => 'required',
		'idjabfungum' => 'required',
		'idjabnonjob' => 'required',
		'iddesa' => 'required',
		'nmadesa' => 'required',
		'tmpidjenjab' => 'required',
		'tmpidjabjbt' => 'required',
		'tmpidjabfung' => 'required',
		'tmpidjabfungum' => 'required',
		'tmpidesljbt' => 'required',
		'tmtjbt' => 'required',
		'tmtjabfung' => 'required',
		'nolantikjbt' => 'required',
		'tglantikjbt' => 'required',
		'tunjjbt' => 'required',
		'idsumpahjbt' => 'required',
		'noskmutasijbt' => 'required',
		'tglskmutasijbt' => 'required',
		'tmtmutasijbt' => 'required',
		'idtkpendid' => 'required',
		'idjenjurusan' => 'required',
		'idalmamater' => 'required',
		'thijaz' => 'required',
		'noijaz' => 'required',
		'namasekolah' => 'required',
		'almsekolah' => 'required',
		'kepsek' => 'required',
		'idtkpendidawal' => 'required',
		'idjenjurusanawal' => 'required',
		'thijazawal' => 'required',
		'noijazawal' => 'required',
		'namasekolahawal' => 'required',
		'almsekolahawal' => 'required',
		'kepsekawal' => 'required',
		'flag_dikprajab' => 'required',
		'iddikstru' => 'required',
		'nmdikstru' => 'required',
		'tmdikstru' => 'required',
		'penyelenggara_dikstru' => 'required',
		'angkatan_dikstru' => 'required',
		'tgmul_dikstru' => 'required',
		'tgsel_dikstru' => 'required',
		'jamhari_dikstru' => 'required',
		'nosttp_dikstru' => 'required',
		'tgsttp_dikstru' => 'required',
		'iddikfung' => 'required',
		'nmdikfung' => 'required',
		'tmdikfung' => 'required',
		'penyelenggara_dikfung' => 'required',
		'angkatan_dikfung' => 'required',
		'tgmul_dikfung' => 'required',
		'tgsel_dikfung' => 'required',
		'jamhari_dikfung' => 'required',
		'nosttp_dikfung' => 'required',
		'tgsttp_dikfung' => 'required',
		'iddiktek' => 'required',
		'nmdiktek' => 'required',
		'tmdiktek' => 'required',
		'penyelenggara_diktek' => 'required',
		'angkatan_diktek' => 'required',
		'tgmul_diktek' => 'required',
		'tgsel_diktek' => 'required',
		'jamhari_diktek' => 'required',
		'nosttp_diktek' => 'required',
		'tgsttp_diktek' => 'required',
		'gaji' => 'required',
		'gajidasar' => 'required',
		'flagkaris' => 'required',
		'tmtpensiun' => 'required',
		'mkthnpns' => 'required',
		'mkblnpns' => 'required',
		'nmissu' => 'required',
		'tmlhrissu' => 'required',
		'tglhrissu' => 'required',
		'tgnikah' => 'required',
		'pendidumissu' => 'required',
		'pekerissu' => 'required',
		'nipnrpissu' => 'required',
		'tunjissu' => 'required',
		'rwthukdis' => 'required',
		'tgcerai' => 'required',
		'noskcerai' => 'required',
		'tmtkgbnext' => 'required',
		'mkblnkgb' => 'required',
		'mkthnkgb' => 'required',
		'pejkgb' => 'required',
		'pejpkt' => 'required',
		'idgaji' => 'required',
		'kdgaji' => 'required',
		'karpeg_bu' => 'required',
		'idjenhukum' => 'required',
		'tmthukdis1' => 'required',
		'tmthukdis2' => 'required',
		'email' => 'required',
		'kel' => 'required',
		'nopak' => 'required',
		'tgpak' => 'required',
		'tghonorer' => 'required',
		'lokdikstru' => 'required',
		'idjenharga' => 'required',
		'tgjenharga' => 'required',
		'tgjenhukum' => 'required',
		'lokber' => 'required',
		'idskpd1' => 'required',
		'idjenpens' => 'required',
		'tmtpens' => 'required',
		'noskpens' => 'required',
		'tglskpens' => 'required',
		'tglpens' => 'required',
		'jbtpenetapens' => 'required',
		'ketpens' => 'required',
		'tglmeninggal' => 'required',
		'tglujikesehatan' => 'required',
		'penerimapensiun' => 'required',
		'tmtmasuk' => 'required',
		'iskepsek' => 'required',
		'idkepsek' => 'required',
		'tmtkepsek' => 'required',
		'noskkepsek' => 'required',
		'idmatkulpel' => 'required',
		'idtugasgurudosen' => 'required',
		'idtugasdokter' => 'required',
		'isdiperbantukan' => 'required',
		'iddiperbantukan' => 'required',
		'tinggi' => 'required',
		'berat' => 'required',
		'rambut' => 'required',
		'muka' => 'required',
		'kulit' => 'required',
		'ciri' => 'required',
		'cacat' => 'required',
		'hobby1' => 'required',
		'hobby2' => 'required',
		'hobby3' => 'required',
		'mkthpns' => 'required',
		'mktbpns' => 'required',
		'akret' => 'required',
		'usiapens' => 'required',
		'id_presensi' => 'required',
		'imei' => 'required',
		'id_sapk' => 'required',
		'user_id' => 'required',
		'role_id' => 'required',
		'created_at' => 'required',
		'updated_at' => 'required',

    );

	public static function all($columns = array('*')){
		$instance = new static;
		if (\PermissionsLibrary::hasPermission('mod-nominatifpenjagaanpkpppk-listall')){
			return $instance->newQuery()->paginate($_ENV['configurations']['list-limit']);
		}else{
			return $instance->newQuery()
			->where('role_id', \Session::get('role_id'))
			->paginate($_ENV['configurations']['list-limit']);	
			
		}
	}

}
