<?php
    use rizalafani\fpdflaravel\Fpdf as FPDFS;
    
    class PDF_MC_Table extends FPDFS{
        var $widths;
        var $aligns;

        function Header()
        {
            // Logo
            $this->Image('http://www.fpdf.org/en/tutorial/logo.png',10,6,30);
            // Arial bold 15
            $this->SetFont('Arial','B',15);
            // Move to the right
            $this->Cell(60);
            // Title
            $this->Cell(80,10,'LAPORAN PEGAWAI',1,0,'C');
            // Line break
            $this->Ln(20);
        }

        function Footer(){
            $this->SetY(-9);
            $this->SetFont('Arial', '', 7);
            $this->SetFont('Arial', '', 7);
            $this->Cell(70, 10, 'Hal. : ' . $this->PageNo(), 0, 0, 'L');
            /*$this->Cell(50, 4, 'JP = Jumlah Pertemuan Total', 0, 0, 'L');*/
            $this->SetFont('Arial', 'I', 7);
            $this->Cell(130, 10, 'printed on : ' . date('d-m-Y H:i') . ' wib | Generated by eSimpeg', 0, 1, 'R');
        }

        function SetWidths($w){
            $this->widths=$w;
        }

        function SetAligns($a){
            $this->aligns=$a;
        }

        function Row($data){
            $nb=0;
            for($i=0;$i<count($data);$i++)
                $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
            $h=8*$nb;
            //Issue a page break first if needed
            $this->CheckPageBreak($h);
            //Draw the cells of the row
            for($i=0;$i<count($data);$i++)
            {
                $w=$this->widths[$i];
                $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
                //Save the current position
                $x=$this->GetX();
                $y=$this->GetY();
                //Draw the border
                $this->Rect($x,$y,$w,$h);
                //Print the text
                $this->MultiCell($w,8,$data[$i],0,$a);
                //Put the position to the right of the cell
                $this->SetXY($x+$w,$y);
            }
            //Go to the next line
            $this->Ln($h);
        }

        function RowNoLines($data){
            $nb=0;
            for($i=0;$i<count($data);$i++)
                $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
            $h=8*$nb;
            //Issue a page break first if needed
            $this->CheckPageBreak($h);
            //Draw the cells of the row
            for($i=0;$i<count($data);$i++)
            {
                $w=$this->widths[$i];
                $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
                //Save the current position
                $x=$this->GetX();
                $y=$this->GetY();
                //Draw the border
    //            $this->Rect($x,$y,$w,$h);
                //Print the text
                $this->MultiCell($w,8,$data[$i],0,$a);
                //Put the position to the right of the cell
                $this->SetXY($x+$w,$y);
            }
            //Go to the next line
            $this->Ln($h);
        }

        function CheckPageBreak($h){
            //If the height h would cause an overflow, add a new page immediately
            if($this->GetY()+$h>$this->PageBreakTrigger)
                $this->AddPage($this->CurOrientation);
        }

        function NbLines($w,$txt){
            //Computes the number of lines a MultiCell of width w will take
            $cw=&$this->CurrentFont['cw'];
            if($w==0)
                $w=$this->w-$this->rMargin-$this->x;
            $wmax=($w-2*$this->cMargin)*1000/$this->FontSize;
            $s=str_replace("\r",'',$txt);
            $nb=strlen($s);
            if($nb>0 and $s[$nb-1]=="\n")
                $nb--;
            $sep=-1;
            $i=0;
            $j=0;
            $l=0;
            $nl=1;
            while($i<$nb){
                $c=$s[$i];
                if($c=="\n"){
                    $i++;
                    $sep=-1;
                    $j=$i;
                    $l=0;
                    $nl++;
                    continue;
                }
                if($c==' ')
                    $sep=$i;
                $l+=$cw[$c];
                if($l>$wmax){
                    if($sep==-1){
                        if($i==$j)
                            $i++;
                    }
                    else
                        $i=$sep+1;
                    $sep=-1;
                    $j=$i;
                    $l=0;
                    $nl++;
                }
                else
                    $i++;
            }
            return $nl;
        }
    }
    
    // Load data
    function LoadData($file)
    {
        // Read file lines
        $lines = file($file);
        $data = array();
        foreach($lines as $line)
            $data[] = explode(';',trim($line));
        return $data;
    }

    $pdf = new PDF_MC_Table('P', 'mm', array(210, 297));

    $pdf->SetAutoPageBreak(true, 5);
    $pdf->SetMargins(5, 8, 10);

    $pdf->AddPage();
    // Arial bold 15
    $pdf->SetFont('Arial', 'B', 12);
    // Title
    $pdf->Cell(200, 7, 'DAFTAR PEGAWAI NEGERI SIPIL ', 'BT', 1, 'C');
    $pdf->Cell(100, 7, 'TEST GOOD', 'BT', 0, 'L');
    $pdf->Cell(100, 7, 'GOOT TEST', 'BT', 1, 'R');
    $h = date('N');

    // Instanciation of inherited class        
    $pdf->SetFont('Times','',12);    
    
//    $pdf->SetDrawColor(0,80,180);
//    $pdf->SetFillColor(230,230,0);
//    $pdf->SetTextColor(220,50,50);
    
    for($i=1;$i<=10;$i++)    
    $pdf->Cell(0,10,'Printing line number '.$i,0,1);    
    
    $no=1;
    
    /*table*/
    $pdf->AddPage('P');
    $pdf->SetFont('Arial', 'BU', 12);
    $pdf->Cell(190, 7, 'LAPORAN KEPEGAWAIAN', 0, 1, 'C');
    $pdf->SetFont('Arial', 'B', 11);
    $pdf->Cell(190, 7, ' JANUARI S/D DESEMBER', 0, 1, 'C');
    
    $sal = 0;
    $saldoawal = 0;
    $temp_bulan = '';
    $pdf->Ln(5);
    $pdf->SetFont('Arial', 'B',8);
//    $pdf->Cell(11,7,12,0,0,'L');
//    $pdf->Cell(50,7,'test',0,1,'L');
//    $pdf->Ln(2);
    $pdf->SetFont('Arial', '',7.5);
    $pdf->SetWidths(array(9,17,20,32,50,22,22,27));
    $pdf->SetAligns(array('c','C','C','C','C','C','C','C'));
    $pdf->Row(array('NO','TGL','NO AGENDA','NO BUKTI','URAIAN','DEBET','KREDIT','SALDO'));
    $pdf->SetAligns(array('C','L','L','L','L','R','R','R'));       

    $rs = \DB::table('tb_01')->take(20)->get();
    $x = 0;
    foreach($rs as $item)
    {
        $x++;
        $pdf->Cell(9,6,$x,'LR');
        $pdf->Cell(17,6,$item->tglhr,'LR');
        $pdf->Cell(20,6,$item->niplama,'LR');
        $pdf->Cell(32,6,$item->nip,'LR',0,'L');
        $pdf->Cell(50,6,$item->nama,'LR',0,'L');
        $pdf->Cell(22,6,$item->telp,'LR',0,'L');
        $pdf->Cell(22,6,$item->telp,'LR',0,'L');
        $pdf->Cell(27,6,$item->telp,'LR',0,'L');
        $pdf->Ln();
    }    
    
    foreach($rs as $item)
    {
        $x++;
        $pdf->Row(array($x,$item->tglhr, $item->niplama, $item->nip, $item->nama, $item->telp, $item->telp, $item->telp));
    }   
    
    $pdf->Cell(172, 7, 'Saldo Awal', 1, 0, 'L');
    $pdf->Cell(27, 7, number_format('1000000'), 1, 1, 'R');
    
    $pdf->Output('Laporan Kepegawaian', 'I');
?>