<?php
    use rizalafani\fpdflaravel\Fpdf as FPDFS;

   class PDF_MC_Table extends FPDFS{
      var $widths;
      var $aligns;

        function Header()
        {
            // Logo
               // $this->Image('http://www.fpdf.org/en/tutorial/logo.png',10,6,30);
            // Arial bold 8
               // $this->SetFont('Arial','B',8);
            // Move to the right
               // $this->Cell(140);
            // Title
               // $this->Cell(30,5,'Form model D.K',1,0,'C');
            // Line break
               // $this->Ln(5);
            //--------------------------------------------------------------
            // Arial bold 11
               // $this->SetFont('Arial', 'B', 12);
            // Title
               // $this->Cell(200, 5, 'SURAT KETERANGAN ', 0, 1, 'C');
               // $this->SetFont('Arial', 'BU', 12);
               // $this->Cell(190, 5, 'UNTUK MENDAPATKAN PEMBAYARAN TUNJANGAN KELUARGA', 0, 1, 'C');
        }

        function Footer(){
            /*$this->SetY(-9);
            $this->SetFont('Arial', '', 7);
            $this->SetFont('Arial', '', 7);
            $this->Cell(60, 10, 'Hal. : ' . $this->PageNo(), 0, 0, 'L');*/
            /*$this->Cell(50, 4, 'JP = Jumlah Pertemuan Total', 0, 0, 'L');*/
            /*$this->SetFont('Arial', 'I', 7);
            $this->Cell(110, 10, 'printed on : ' . date('d-m-Y H:i') . ' wib | Generated by eSimpeg', 0, 1, 'R');*/
        }

        function SetWidths($w){
            $this->widths=$w;
        }

        function SetAligns($a){
            $this->aligns=$a;
        }

        function Row($data){
            $nb=0;
            for($i=0;$i<count($data);$i++)
                $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
            //jarak tabel
            $h=5*$nb;
            //Issue a page break first if needed
            $this->CheckPageBreak($h);
            //Draw the cells of the row
            for($i=0;$i<count($data);$i++)
            {
                $w=$this->widths[$i];
                $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
                //Save the current position
                $x=$this->GetX();
                $y=$this->GetY();
                //Draw the border
                $this->Rect($x,$y,$w,$h);
                //Print the text
                //jarak tulisan dalam tabel
                $this->MultiCell($w,5,$data[$i],0,$a);
                //Put the position to the right of the cell
                $this->SetXY($x+$w,$y);
            }
            //Go to the next line
            $this->Ln($h);
        }

        function RowNoLines($data){
            $nb=0;
            for($i=0;$i<count($data);$i++)
                $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
            //jarak tabel
            $h=5*$nb;
            //Issue a page break first if needed
            $this->CheckPageBreak($h);
            //Draw the cells of the row
            for($i=0;$i<count($data);$i++)
            {
                $w=$this->widths[$i];
                $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
                //Save the current position
                $x=$this->GetX();
                $y=$this->GetY();
                //Draw the border
                //$this->Rect($x,$y,$w,$h);
                //Print the text
                //jarak tulisan dalam tabel
                $this->MultiCell($w,5,$data[$i],0,$a);
                //Put the position to the right of the cell
                $this->SetXY($x+$w,$y);
            }
            //Go to the next line
            $this->Ln($h);
        }

        function CheckPageBreak($h){
            //If the height h would cause an overflow, add a new page immediately
            if($this->GetY()+$h>$this->PageBreakTrigger)
                $this->AddPage($this->CurOrientation);
        }

        function NbLines($w,$txt){
            //Computes the number of lines a MultiCell of width w will take
            $cw=&$this->CurrentFont['cw'];
            if($w==0)
                $w=$this->w-$this->rMargin-$this->x;
            $wmax=($w-2*$this->cMargin)*1000/$this->FontSize;
            $s=str_replace("\r",'',$txt);
            $nb=strlen($s);
            if($nb>0 and $s[$nb-1]=="\n")
                $nb--;
            $sep=-1;
            $i=0;
            $j=0;
            $l=0;
            $nl=1;
            while($i<$nb){
                $c=$s[$i];
                if($c=="\n"){
                    $i++;
                    $sep=-1;
                    $j=$i;
                    $l=0;
                    $nl++;
                    continue;
                }
                if($c==' ')
                    $sep=$i;
                $l+=$cw[$c];
                if($l>$wmax){
                    if($sep==-1){
                        if($i==$j)
                            $i++;
                    }
                    else
                        $i=$sep+1;
                    $sep=-1;
                    $j=$i;
                    $l=0;
                    $nl++;
                }
                else
                    $i++;
            }
            return $nl;
        }
   }

   // Load data
   function LoadData($file)
   {
      // Read file lines
      $lines = file($file);
      $data = array();
      foreach($lines as $line)
         $data[] = explode(';',trim($line));
      return $data;
   }


   // $pdf = new PDF_MC_Table('P', 'mm', array(210, 297));
   $pdf = new PDF_MC_Table('P', 'mm', array(215, 279));

   $pdf->SetAutoPageBreak(true, 5);

   $where = " tb_01.idjenkedudupeg not in (99,21)";
   $nip = \Request::segment(4);
   ($nip!='')?$where.=" and tb_01.nip = '".$nip."'":"";

   $biodata = \DB::table('tb_01')
       ->select('tb_01.*','a_golruang.golru','a_golruang.pangkat','a_skpd.path_short','a_esl.esl','a_tkpendid.tkpendid','a_jenjurusan.jenjurusan','a_jenkepeg.jenkepeg','a_jenkedudupeg.jenkedudupeg',
           \DB::raw('CONCAT(tb_01.gdp,IF(LENGTH(tb_01.gdp)>0," ",""),tb_01.nama,IF(LENGTH(tb_01.gdb)>0,", "," "),tb_01.gdb) as namalengkap'),'a_jenkel.jenkel','a_agama.agama',
           \DB::raw('IF(tb_01.idjenjab>4,a_skpd.jab,IF(tb_01.idjenjab=2,a_jabfung.jabfung,IF(tb_01.idjenjab=3,a_jabfungum.jabfungum,IF(tb_01.idjenjab=4,a_jabnonjob.jabnonjob,"-")))) as jabatan'),
           \DB::raw("
               CONCAT(
                   IF((LEFT(tb_01.idgolrupkt,1) != LEFT(idgolrucpn,1)),
                       (SUBSTR(DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(IF(tb_01.tmtcpn='0000-00-00',tb_01.tmtpns,tb_01.tmtcpn))), '%Y%m')+0,1,
                           (LENGTH(DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(IF(tb_01.tmtcpn='0000-00-00',tb_01.tmtpns,tb_01.tmtcpn))), '%Y%m')+0)-2))
                           -
                           (IF((LEFT(tb_01.idgolrupkt,1) >= 3 AND LEFT(idgolrucpn,1) = 1), 11 - tb_01.mkthncpn,
                           IF((LEFT(tb_01.idgolrupkt,1) >= 3 AND LEFT(idgolrucpn,1) = 2), 5 - tb_01.mkthncpn,
                              IF((LEFT(tb_01.idgolrupkt,1) = 2 AND LEFT(idgolrucpn,1) = 1), 6 - tb_01.mkthncpn, 0 ))))
                       ),
                       (SUBSTR(DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(IF(tb_01.tmtcpn='0000-00-00',tb_01.tmtpns,tb_01.tmtcpn))), '%Y%m')+0,1,
                           (LENGTH(DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(IF(tb_01.tmtcpn='0000-00-00',tb_01.tmtpns,tb_01.tmtcpn))), '%Y%m')+0)-2))
                           + tb_01.mkthncpn
                       )
                   ),
                   RIGHT(DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(IF(tb_01.tmtcpn='0000-00-00',tb_01.tmtpns,tb_01.tmtcpn))), '%Y%m')+0, 2)) AS mkskr
           "),
           \DB::raw("DATE_FORMAT(FROM_DAYS(TO_DAYS(NOW())-TO_DAYS(tb_01.tglhr)), '%Y%m')+0 AS usia")
       )
       ->leftjoin('a_skpd', 'tb_01.idskpd', '=', 'a_skpd.idskpd')
       ->leftjoin('a_esl', 'tb_01.idesljbt', '=', 'a_esl.idesl')
       ->leftjoin('a_tkpendid', 'tb_01.idtkpendid', '=', 'a_tkpendid.idtkpendid')
       ->leftjoin('a_jenjurusan', 'tb_01.idjenjurusan', '=', 'a_jenjurusan.idjenjurusan')
       ->leftjoin('a_golruang', 'tb_01.idgolrupkt', '=', 'a_golruang.idgolru')
       ->leftjoin('a_agama', 'tb_01.idagama', '=', 'a_agama.idagama')
       ->leftjoin('a_jenkel', 'tb_01.idjenkel', '=', 'a_jenkel.idjenkel')
       ->leftjoin('a_jabfung', 'tb_01.idjabfung', '=', 'a_jabfung.idjabfung')
       ->leftjoin('a_jabfungum', 'tb_01.idjabfungum', '=', 'a_jabfungum.idjabfungum')
       ->leftjoin('a_jabnonjob', 'tb_01.idjabnonjob', '=', 'a_jabnonjob.idjabnonjob')
       ->leftjoin('a_jenkepeg', 'tb_01.idjenkepeg', '=', 'a_jenkepeg.idjenkepeg')
       ->leftjoin('a_jenkedudupeg', 'tb_01.idjenkedudupeg', '=', 'a_jenkedudupeg.idjenkedudupeg')
       ->whereRaw($where)
       ->orderBy(\DB::raw('tb_01.idgolrupkt desc,tb_01.tmtpkt,tb_01.idjenjab,tb_01.idesljbt,tb_01.tmtesljbt,tb_01.tmtcpn,tb_01.idtkpendid desc,tb_01.thijaz,tb_01.tglhr'))
       ->first();

   if(count($biodata) == '1'){
      $pdf->SetMargins(15, 8, 12);

      // Instanciation of inherited class
      $pdf->SetFont('Times','',12);

      $pdf->AddPage('P');

      // judul
      $pdf->SetFont('Arial','B',8);
      $pdf->Cell(140);
      $pdf->Cell(30,5,'Form model D.K',1,0,'C');
      $pdf->Ln(5);
      //--------------------------------------------------------------
      $pdf->SetFont('Arial', 'B', 12);
      $pdf->Cell(200, 5, 'SURAT KETERANGAN ', 0, 1, 'C');
      $pdf->SetFont('Arial', 'BU', 12);
      $pdf->Cell(190, 5, 'UNTUK MENDAPATKAN PEMBAYARAN TUNJANGAN KELUARGA', 0, 1, 'C');

      // isi
      $pdf->Ln(5);
      $pdf->SetFont('Arial', '',8.5);
      $pdf->SetWidths(array(65,5,120));
      $pdf->SetAligns(array('L','C','L'));
      $pdf->RowNoLines(array('NAMA OPD',':',strtoupper($biodata->path_short)));
      $pdf->RowNoLines(array('ALAMAT LENGKAP',':','JL. SOEKARNO HATTA 193 KENDAL'));
      $pdf->RowNoLines(array('INSTANSI INDUK',':','PEMERINTAH DAERAH KABUPATEN KENDAL'));
      $pdf->SetWidths(array(65,5,55,5,7,5,48));
      $pdf->SetAligns(array('L','C','L','L','L','C','L'));
      $pdf->RowNoLines(array('BENDAHARA PEMBANTU GAJI',':','SRI RAHAYU','','NIP',':','198005102008012016'));
      $pdf->RowNoLines(array('DATA PEGAWAI','','','','','',''));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','1.','Nama Lengkap',':',$biodata->namalengkap));
      $pdf->SetWidths(array(3,7,55,5,40,5,75));
      $pdf->SetAligns(array('L','L','L','C','L','C','L'));
      $pdf->RowNoLines(array('','2.','NIP / NPWD',':',$biodata->nip,'/','48.379.434.3.-503.000'));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','3.','Pangkat Golongan Ruang',':',$biodata->pangkat.' ('.$biodata->golru.') '));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','4.','TMT Golongan Ruang',':',(($biodata->tmtpkt!='0000-00-00')?formatTanggalPanjang($biodata->tmtpkt):'')));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','5.','Tempat, Tanggal Lahir',':',$biodata->tmlhr.', '.(($biodata->tglhr!='0000-00-00')?formatTanggalPanjang($biodata->tglhr):'')));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','6.','Jenis Kelamin',':',$biodata->jenkel));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','7.','Agama / Kebangsaan',':',$biodata->agama.' / Indonesia'));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','8.','Alamat Lengkap',':', $biodata->alm));
      $pdf->RowNoLines(array('','','','', (($biodata->almrt!="")? 'RT. '.$biodata->almrt:"").' '.(($biodata->almrt!="" && $biodata->almrw!="" )? '/':'').' '.(($biodata->almrw!="")? 'RW. '.$biodata->almrw:'')));
      $pdf->RowNoLines(array('','','','', (($biodata->almdesa!='')? 'Desa / Kelurahan *) '.$biodata->almdesa.'':'').' '.(($biodata->almkdpos!='')? 'Kode Pos.'.$biodata->almkdpos.'':'')));
      $pdf->RowNoLines(array('','','','', (($biodata->almkec!='')? 'Kec. '.$biodata->almkec.'':'')));
      $pdf->RowNoLines(array('','','','', (($biodata->almkab!='')? 'Kabupaten / Kota *) '.ucword(strtolower($biodata->almkab)).'':'')));
      $pdf->RowNoLines(array('','','','', (($biodata->almprov!='')? 'Prov. '.$biodata->almprov.'':'')));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','9.','TMT Capeg',':','01-April-2006'));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','10.','Jenis Kepegawaian',':',$biodata->jenkepeg));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','11.','Status Kepegawaian',':',$biodata->jenkedudupeg));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','12.','Digaji Menurut',':','PP No. 30 Tahun 2015 Gaji Pokok Rp. 3.021.300,-'));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','13.','Besarnya Penghasilan Bruto',':','Rp. 4.384.689,-'));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','14.','Jabatan Struktural / Fungsional *)',':',$biodata->jabatan));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','15.','Jumlah Keluarga Tertanggung',':','3 (tiga) Orang'));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','16.','SK terakhir yang dimiliki',':','SK Kenaikan Gaji Berkali'));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','17.','Masa Kerja Golongan',':',$biodata->mkthnpkt.' TAHUN '.$biodata->mkblnpkt.' BULAN'));
      $pdf->SetWidths(array(3,7,55,5,120));
      $pdf->SetAligns(array('L','L','L','C','L'));
      $pdf->RowNoLines(array('','','Masa Kerja Keseluruhan',':',substr($biodata->mkskr,0,-2).' TAHUN '.substr($biodata->mkskr,-2).' BULAN'));

      $pdf->Ln(5);
      $pdf->SetFont('Arial', '',8);
      $pdf->SetWidths(array(190));
      $pdf->SetAligns(array('J'));
      $pdf->RowNoLines(array('Keterangan ini saya buat dengan sesungguhnya dan apabila keterangan ini tidak benar (palsu), Saya bersedia dituntut di muka pengadilan berdasarkan undag-undang yang berlaku, dan bersedia mengembalikan semua uang tunjangan yang telah Saya terima yang seharusnya bukan menjadi hak milik saya.'));

      $pdf->Ln(7);
      $pdf->SetFont('Arial', '',8);
      $pdf->SetWidths(array(135,55));
      $pdf->SetAligns(array('L','L'));
      $pdf->RowNoLines(array('','Kendal, '.date('d-m-Y')));
      $pdf->SetWidths(array(45,90,55));
      $pdf->SetAligns(array('C','L','L'));
      $pdf->RowNoLines(array('Mengetahui / Mengesahkan','','Pegawai yang bersangkutan'));
      $pdf->SetWidths(array(45,145));
      $pdf->SetAligns(array('C'));
      $pdf->RowNoLines(array('Kepala OPD',''));

      $pdf->Ln(18);
      $pdf->SetFont('Arial', 'BU',8);
      $pdf->SetWidths(array(45,90,55));
      $pdf->SetAligns(array('C','L','L'));
      $pdf->RowNoLines(array(getKepskpd($biodata->idskpd,'nama'),'',$biodata->namalengkap));
      $pdf->SetFont('Arial', '',8);
      $pdf->SetWidths(array(45,90,55));
      $pdf->SetAligns(array('C','L','L'));
      $pdf->RowNoLines(array('NIP.'.getKepskpd($biodata->idskpd,'nip'),'','NIP.'.$biodata->nip));

      $pdf->Ln(16);
      $pdf->SetFont('Arial', '',7);
      $pdf->SetWidths(array(190));
      $pdf->SetAligns(array('L'));
      $pdf->RowNoLines(array('Catatan : '));
      $pdf->RowNoLines(array('*) Coret yang tidak perlu'));

      /* End footer*/
      $pdf->SetY(263);
      $pdf->SetFont('Arial', '', 7);
      $pdf->SetFont('Arial', '', 7);
      $pdf->Cell(60, 10, 'Hal. : ' . $pdf->PageNo(), 0, 0, 'L');
      /*$this->Cell(50, 4, 'JP = Jumlah Pertemuan Total', 0, 0, 'L');*/
      $pdf->SetFont('Arial', 'I', 7);
      $pdf->Cell(125, 10, 'printed on : ' . date('d-m-Y H:i') . ' wib | Generated by eSimpeg', 0, 1, 'R');
      /* End footer*/

      // halaman II--------------------------------------------------
      $pdf->SetMargins(23, 10, 12);
      $pdf->AddPage('L');

      // judul
      $pdf->SetFont('Arial', 'B', 12);
      $pdf->Cell(200, 5, 'DATA KELUARGA YANG MENJADI TANGGUNGAN PEGAWAI', 0, 1, 'L');
      $pdf->Ln(4);
      $pdf->SetFont('Arial', '', 12);
      $pdf->Cell(190, 5, 'A. KAWIN SYAH DENGAN SUAMI/ISTERI', 0, 1, 'L');

      // start isi tabel 1
      $pdf->SetFont('Arial', 'B',8);
      $x = $pdf->GetX();
      $y = $pdf->GetY();

      $pdf->SetXY(13,28);
      $pdf->MultiCell(7,15,'NO',1,'C');
      $pdf->SetXY(20,28);
      $pdf->MultiCell(52,15,'NAMA SUAMI / ISTERI','TRB','C');
      $pdf->SetXY(72,28);
      $pdf->MultiCell(20,12,'TEMPAT','TR','C');
      $pdf->SetXY(72,34.5);
      $pdf->MultiCell(20,8.5,'LAHIR','RB','C');
      $pdf->SetXY(92,28);
      $pdf->MultiCell(28,15,'TANGGAL LAHIR','TRB','C');
      $pdf->SetXY(120,28);
      $pdf->MultiCell(36,15,'NIP / NIK','TRB','C');
      $pdf->SetXY(156,28);
      $pdf->MultiCell(27,15,'PEKERJAAN','TRB','C');
      $pdf->SetXY(183,28);
      $pdf->MultiCell(28,12,'TANGGAL','TR','C');
      $pdf->SetXY(183,34.5);
      $pdf->MultiCell(28,8.5,'PERKAWINAN','RB','C');
      $pdf->SetXY(211,28);
      $pdf->MultiCell(28,15,'SUAMI / ISTERI KE','TRB','C');
      $pdf->SetXY(239,28);
      $pdf->MultiCell(34,12,'PENGHASILAN PER','TR','C');
      $pdf->SetXY(239,34.5);
      $pdf->MultiCell(34,8.5,'BULAN','RB','C');

      $pdf->SetMargins(13, 10, 10);
      $pdf->Ln(0);
      $pdf->SetFont('Arial', 'B',7.6);
      $pdf->SetWidths(array(7,52,20,28,36,27,28,28,34));
      $pdf->SetAligns(array('C','L','C','C','C','L','C','C','C'));

      //ambil data
      ($nip!='')?$whr ="r_issu.nip = '".$nip."'":"";

      $bio_issu = \DB::table('r_issu')
                  ->select('r_issu.*')
                  ->whereRaw($whr)
                  ->get();

      //cek apakah ada data istri / suami(mempunyai / tidak)
      if(count($bio_issu) > 0){
         //mempunyai istri / suami
         //cek ada berapakah data istri / suami
         if(count($bio_issu) == 1){
            //mempunyai istri / suami == 1
            $no=1;
            foreach ($bio_issu as $key => $issu) {
               $pdf->row(array($no,ucword(strtolower($issu->nmissu)),ucword(strtolower($issu->tmlhr)),(($issu->tglhr!='0000-00-00')?formatTanggalPanjang($issu->tglhr):'-'),($issu->nipnrp!='')? $issu->nipnrp:'-',($issu->peker==1)?'PNS Kab.Kendal':($issu->peker==2)?'PNS Luar Kab.Kendal':'Non PNS',(($issu->tgnikah!='0000-00-00')?formatTanggalPanjang($issu->tgnikah):'-'),'',''));

               $no++;
            }
            $pdf->row(array('','','','','','','','',''));
            $pdf->row(array('','','','','','','','',''));
         }else if(count($bio_issu) == 2){
            //mempunyai istri / suami == 2
            $no=1;
            foreach ($bio_issu as $key => $issu) {
               $pdf->row(array($no,ucword(strtolower($issu->nmissu)),ucword(strtolower($issu->tmlhr)),(($issu->tglhr!='0000-00-00')?formatTanggalPanjang($issu->tglhr):'-'),($issu->nipnrp!='')? $issu->nipnrp:'-',($issu->peker==1)?'PNS Kab.Kendal':($issu->peker==2)?'PNS Luar Kab.Kendal':'Non PNS',(($issu->tgnikah!='0000-00-00')?formatTanggalPanjang($issu->tgnikah):'-'),'',''));

               $no++;
            }
               $pdf->row(array('','','','','','','','',''));
         }else if(count($bio_issu) > 2) {
            //mempunyai istri / suami > 2
            $no=1;
            foreach ($bio_issu as $key => $issu) {
               $pdf->row(array($no,ucword(strtolower($issu->nmissu)),ucword(strtolower($issu->tmlhr)),(($issu->tglhr!='0000-00-00')?formatTanggalPanjang($issu->tglhr):'-'),($issu->nipnrp!='')? $issu->nipnrp:'-',($issu->peker==1)?'PNS Kab.Kendal':($issu->peker==2)?'PNS Luar Kab.Kendal':'Non PNS',(($issu->tgnikah!='0000-00-00')?formatTanggalPanjang($issu->tgnikah):'-'),'',''));

               $no++;
            }
         }else{
            //tidak mmempunyai istri / suami
            $pdf->row(array('','','','','','','','',''));
            $pdf->row(array('','','','','','','','',''));
            $pdf->row(array('','','','','','','','',''));
         }
      }else{
         //tidak mmempunyai istri / suami
         $pdf->row(array('','','','','','','','',''));
         $pdf->row(array('','','','','','','','',''));
         $pdf->row(array('','','','','','','','',''));
      }
      // end isi tabel 1

      $pdf->SetMargins(23, 10, 12);
      $pdf->Ln(7);
      $pdf->SetFont('Arial', '', 12);
      $pdf->Cell(190, 5, 'B. ANAK-ANAK YANG MENJADI TANGGUNGAN', 0, 1, 'L');

      $pdf->SetMargins(28.5, 10, 12);
      $pdf->Ln(0);
      $pdf->SetFont('Arial', '', 11);
      $pdf->Cell(190, 5, 'Mempunyai anak-anak yang seperti dalam daftar di bawah ini, yaitu :', 0, 1, 'L');
      $pdf->Cell(190, 5, 'Anak Kandung (ak) Anak Angkat (aa) yang menjadi tanggungan belum mempunyai pekerjaan sendiri dan masuk dalam Daftar Gaji', 0, 1, 'L');
      $pdf->Cell(190, 5, 'Anak Kandung (ak) Anak Angkat (aa) yang menjadi tanggungan tetapi tidak masuk dalam Daftar Gaji', 0, 1, 'L');

      // start isi tabel 2
      $pdf->SetFont('Arial', 'B',8);
      $x = $pdf->GetX();
      $y = $pdf->GetY();

      $pdf->SetXY(13,96);
      $pdf->MultiCell(7,19,'NO',1,'C');
      $pdf->SetXY(20,96);
      $pdf->MultiCell(45,19,'NAMA ANAK','TRB','C');
      $pdf->SetXY(65,96);
      $pdf->MultiCell(20,16,'TEMPAT','TR','C');
      $pdf->SetXY(65,102.5);
      $pdf->MultiCell(20,12.5,'LAHIR','RB','C');
      $pdf->SetXY(85,96);
      $pdf->MultiCell(20,16,'TANGGAL','TR','C');
      $pdf->SetXY(85,102.5);
      $pdf->MultiCell(20,12.5,'LAHIR','RB','C');
      $pdf->SetXY(105,96);
      $pdf->MultiCell(24,19,'STATUS ANAK','TRB','C');
      $pdf->SetXY(129,96);
      $pdf->MultiCell(20,6,'DARI','TR','C');
      $pdf->SetXY(129,100.5);
      $pdf->MultiCell(20,6,'ISTERI /','R','C');
      $pdf->SetXY(129,104.5);
      $pdf->MultiCell(20,6,'SUAMI','R','C');
      $pdf->SetXY(129,108.5);
      $pdf->MultiCell(20,6.5,'KE','RB','C');
      $pdf->SetXY(149,96);
      $pdf->MultiCell(20,16,'JENIS','TR','C');
      $pdf->SetXY(149,102.5);
      $pdf->MultiCell(20,12.5,'KELAMIN','RB','C');
      $pdf->SetXY(169,96);
      $pdf->MultiCell(24,16,'DAPAT / TIDAK','TR','C');
      $pdf->SetXY(169,102.5);
      $pdf->MultiCell(24,12.5,'TUNJ','RB','C');
      $pdf->SetXY(193,96);
      $pdf->MultiCell(30,10,'SUDAH / BELUM','TRB','C');
      $pdf->SetXY(193,106);
      $pdf->MultiCell(14,9,'KAWIN','RB','C');
      $pdf->SetXY(207,106);
      $pdf->MultiCell(16,9,'BEKERJA','RB','C');
      $pdf->SetXY(223,96);
      $pdf->MultiCell(20,6,'MASIH /','TR','C');
      $pdf->SetXY(223,100.5);
      $pdf->MultiCell(20,6,'TIDAK','R','C');
      $pdf->SetXY(223,104.5);
      $pdf->MultiCell(20,6,'SEK /','R','C');
      $pdf->SetXY(223,108.5);
      $pdf->MultiCell(20,6.5,'KULIAH','RB','C');
      $pdf->SetXY(243,96);
      $pdf->MultiCell(29,8.5,'PUTUSAN','TR','C');
      $pdf->SetXY(243,102.5);
      $pdf->MultiCell(29,8.5,'PENGADILAN','R','C');
      $pdf->SetXY(243,106.5);
      $pdf->MultiCell(29,8.5,'(KHUSUS aa)','RB','C');

      $pdf->SetMargins(13, 10, 10);
      $pdf->Ln(0);
      $pdf->SetFont('Arial', 'B',7);
      $pdf->SetWidths(array(7,45,20,20,24,20,20,24,14,16,20,29));
      $pdf->SetAligns(array('C','L','L','C','C','C','C','C','C','C','C','C'));

      //ambil data
      ($nip!='')?$wh ="r_anak.nip = '".$nip."'":"";

      $bio_anak = \DB::table('r_anak')
                  ->select('r_anak.*',\DB::raw("if(r_anak.idjenkel=1,'Laki-laki',if(r_anak.idjenkel=2,'Perempuan','')) as jenkel"),\DB::raw("if(r_anak.tunjangan=1,'Dapat',if(r_anak.tunjangan=2,'Tidak','')) as tunjang"))
                  ->whereRaw($wh)
                  ->orderby('r_anak.tglhr','asc')
                  ->get();

      //cek apakah ada data anak (mempunyai / tidak)
      if(count($bio_anak) > 0){
         //mempunyai anak
         //cek ada berapakah data anak
         if(count($bio_anak) == 1){
            //mempunyai anak == 1
            $nmr=1;
            foreach ($bio_anak as $key => $anak) {
               $pdf->row(array($nmr,ucword(strtolower($anak->nmanak)),ucword(strtolower($anak->tmlhr)),(($anak->tglhr!='0000-00-00')?formatTanggalPanjang($anak->tglhr):'-'),ucword(strtolower($anak->stskeluarga)),'1',$anak->jenkel,$anak->tunjang,'Belum','Belum','Masih','-'));

               $nmr++;
            }
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
         }else if(count($bio_anak) == 2){
            //mempunyai anak == 2
            $nmr=1;
            foreach ($bio_anak as $key => $anak) {
               $pdf->row(array($nmr,ucword(strtolower($anak->nmanak)),ucword(strtolower($anak->tmlhr)),(($anak->tglhr!='0000-00-00')?formatTanggalPanjang($anak->tglhr):'-'),ucword(strtolower($anak->stskeluarga)),'1',$anak->jenkel,$anak->tunjang,'Belum','Belum','Masih','-'));

               $nmr++;
            }
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
         }else if(count($bio_anak) == 3) {
            //mempunyai anak == 3
            $nmr=1;
            foreach ($bio_anak as $key => $anak) {
               $pdf->row(array($nmr,ucword(strtolower($anak->nmanak)),ucword(strtolower($anak->tmlhr)),(($anak->tglhr!='0000-00-00')?formatTanggalPanjang($anak->tglhr):'-'),ucword(strtolower($anak->stskeluarga)),'1',$anak->jenkel,$anak->tunjang,'Belum','Belum','Masih','-'));

               $nmr++;
            }
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
         }else if(count($bio_anak) > 3) {
            //mempunyai anak > 3
            $nmr=1;
            foreach ($bio_anak as $key => $anak) {
               $pdf->row(array($nmr,ucword(strtolower($anak->nmanak)),ucword(strtolower($anak->tmlhr)),(($anak->tglhr!='0000-00-00')?formatTanggalPanjang($anak->tglhr):'-'),ucword(strtolower($anak->stskeluarga)),'1',$anak->jenkel,$anak->tunjang,'Belum','Belum','Masih','-'));

               $nmr++;
            }
            $pdf->row(array('','','','','','','','','','','',''));
         }else{
            //tidak mmempunyai anak
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
            $pdf->row(array('','','','','','','','','','','',''));
         }
      }else{
         //tidak mmempunyai anak
         $pdf->row(array('','','','','','','','','','','',''));
         $pdf->row(array('','','','','','','','','','','',''));
         $pdf->row(array('','','','','','','','','','','',''));
         $pdf->row(array('','','','','','','','','','','',''));
         $pdf->row(array('','','','','','','','','','','',''));
         $pdf->row(array('','','','','','','','','','','',''));
      }

      /* start footer*/
      $pdf->SetY(195);
      $pdf->SetFont('Arial', '', 7);
      $pdf->SetFont('Arial', '', 7);
      $pdf->Cell(50, 10, 'Hal. : ' . $pdf->PageNo(), 0, 0, 'L');
      /*$this->Cell(50, 4, 'JP = Jumlah Pertemuan Total', 0, 0, 'L');*/
      $pdf->SetFont('Arial', 'I', 7);
      $pdf->Cell(195, 10, 'printed on : ' . date('d-m-Y H:i') . ' wib | Generated by eSimpeg', 0, 1, 'R');
      /* End footer*/
      // end isi tabel 2

   }else{
      $pdf->SetMargins(15, 8, 12);

      // Instanciation of inherited class
      $pdf->SetFont('Times','',12);

      $pdf->AddPage('P');

      // judul
      $pdf->SetFont('Arial','B',8);
      $pdf->Cell(140);
      $pdf->Cell(30,5,'Form model D.K',1,0,'C');
      $pdf->Ln(5);
      //--------------------------------------------------------------
      $pdf->SetFont('Arial', 'B', 12);
      $pdf->Cell(200, 5, 'SURAT KETERANGAN ', 0, 1, 'C');
      $pdf->SetFont('Arial', 'BU', 12);
      $pdf->Cell(190, 5, 'UNTUK MENDAPATKAN PEMBAYARAN TUNJANGAN KELUARGA', 0, 1, 'C');

      $pdf->Ln(5);
      $pdf->SetFont('Arial', '',8.5);
      $pdf->SetWidths(array(65,5,120));
      $pdf->SetAligns(array('L','C','L'));
      $pdf->RowNoLines(array('Keterangan',':','Data yang anda cari tidak ditemukan'));

      /* Start footer*/
      $pdf->SetY(263);
      $pdf->SetFont('Arial', '', 7);
      $pdf->SetFont('Arial', '', 7);
      $pdf->Cell(60, 10, 'Hal. : ' . $pdf->PageNo(), 0, 0, 'L');
      /*$this->Cell(50, 4, 'JP = Jumlah Pertemuan Total', 0, 0, 'L');*/
      $pdf->SetFont('Arial', 'I', 7);
      $pdf->Cell(125, 10, 'printed on : ' . date('d-m-Y H:i') . ' wib | Generated by eSimpeg', 0, 1, 'R');
      /* End footer*/
   }

   $pdf->Output('SK Mendapatkan Pembayaran Tunjangan Keluarga', 'I');
?>
