<?php

use rizalafani\fpdflaravel\Fpdf as FPDFS;

require app_path() . "/easyTable.php";
require app_path() . "/qrcode/qrcode.class.php";

class exFPDF extends FPDFS
{

    public function Header()
    {

    }

    public function Footer()
    {
        $this->SetY(-9);
        $this->SetFont('Arial', '', 7);
        $this->SetFont('Arial', '', 7);
        $this->Cell(15, 4, 'Hal. : ' . $this->PageNo() . '.', 0, 0, 'L');
        $this->Cell(50, 4, '', 0, 0, 'L');
        $this->SetFont('Arial', 'I', 7);
        $this->Cell(105, 4, 'printed on : ' . date('d-m-Y') . ' | Generated by SIMPEG Kab. Kendal', 0, 1, 'R');
    }

    public function PageBreak()
    {
        return $this->PageBreakTrigger;
    }

    public function current_font($c)
    {
        if ($c == 'family') {
            return $this->FontFamily;
        } elseif ($c == 'style') {
            return $this->FontStyle;
        } elseif ($c == 'size') {
            return $this->FontSizePt;
        }
    }

    public function get_color($c)
    {
        if ($c == 'fill') {
            return $this->FillColor;
        } elseif ($c == 'text') {
            return $this->TextColor;
        }
    }

    public function get_page_width()
    {
        return $this->w;
    }

    public function get_margin($c)
    {
        if ($c == 'l') {
            return $this->lMargin;
        } elseif ($c == 'r') {
            return $this->rMargin;
        } elseif ($c == 't') {
            return $this->tMargin;
        }
    }

    public function get_linewidth()
    {
        return $this->LineWidth;
    }

    public function get_orientation()
    {
        return $this->CurOrientation;
    }
    /***********************************************************************
     *
     * Based on FPDF method SetFont
     *
     ************************************************************************/

    private function &FontData($family, $style, $size)
    {
        if ($family == '') {
            $family = $this->FontFamily;
        } else {
            $family = strtolower($family);
        }

        $style = strtoupper($style);
        if (strpos($style, 'U') !== false) {
            $style = str_replace('U', '', $style);
        }
        if ($style == 'IB') {
            $style = 'BI';
        }

        $fontkey = $family . $style;
        if (!isset($this->fonts[$fontkey])) {
            if ($family == 'arial') {
                $family = 'helvetica';
            }

            if (in_array($family, $this->CoreFonts)) {
                if ($family == 'symbol' || $family == 'zapfdingbats') {
                    $style = '';
                }

                $fontkey = $family . $style;
                if (!isset($this->fonts[$fontkey])) {
                    $this->AddFont($family, $style);
                }

            } else {
                $this->Error('Undefined font: ' . $family . ' ' . $style);
            }

        }
        $result['FontSize'] = $size / $this->k;
        $result['CurrentFont'] = &$this->fonts[$fontkey];
        return $result;
    }

    /***********************************************************************
     *
     * Based on FPDF method MultiCell
     *
     ************************************************************************/

    public function extMultiCell($font_family, $font_style, $font_size, $w, $txt)
    {
        $result = array();
        $font = $this->FontData($font_family, $font_style, $font_size);
        $cw = $font['CurrentFont']['cw'];
        if ($w == 0) {
            return $result;
        }
        $wmax = $w * 1000 / $font['FontSize'];
        $s = trim(str_replace("\r", '', $txt));
        $chs = strlen($s);
        $sep = -1;
        $i = 0;
        $j = 0;
        $l = 0;
        while ($i < $chs) {
            $c = $s[$i];
            if ($c == "\n") {
                $result[] = substr($s, $j, $i - $j);
                $i++;
                $sep = -1;
                $j = $i;
                $l = 0;
                continue;
            }
            if ($c == ' ') {
                if ($l == 0) {
                    while ($s[$i] == ' ') {
                        $i++;
                    }
                    $j = $i;
                }
                $sep = $i;
            }
            $l += $cw[$c];
            if ($l > $wmax) {
                if ($sep == -1) {
                    if ($i == $j) {
                        $i++;
                    }

                    $result[] = substr($s, $j, $i - $j);
                } else {
                    $result[] = substr($s, $j, $sep - $j);
                    $i = $sep + 1;
                }
                $sep = -1;
                $j = $i;
                $l = 0;
            } else {
                $i++;
            }
        }
        $s = trim(substr($s, $j, $i - $j));
        if ($s != '') {
            $result[] = $s;
        }
        return $result;
    }

    /***********************************************************************
     *
     * Based on FPDF method Cell
     *
     ************************************************************************/

    public function CellBlock($w, $h, &$array_txt, $align = 'J', $link = '')
    {
        if (!isset($this->CurrentFont)) {
            $this->Error('No font has been set');
        }

        foreach ($array_txt as $ti => $txt) {
            $k = $this->k;
            if ($this->y + $h > $this->PageBreakTrigger) {
                break;
            }
            if ($w == 0) {
                return;
            }
            $s = '';
            if ($txt !== '') {
                $stringWidth = $this->GetStringWidth($txt);
                if ($align == 'R') {
                    $dx = $w - $stringWidth;
                } elseif ($align == 'C') {
                    $dx = ($w - $stringWidth) / 2;
                } else {
                    $dx = 0;
                }
                if ($align == 'J') {
                    $ns = count(explode(' ', $txt));
                    $wx = $w;
                    $this->ws = ($ns > 1) ? (($wx - $stringWidth) * (1 / ($ns - 1))) : 0;
                    $this->_out(sprintf('%.3F Tw', $this->ws * $this->k));
                }
                if ($this->ColorFlag) {
                    $s .= 'q ' . $this->TextColor . ' ';
                }

                $s .= sprintf('BT %.2F %.2F Td (%s) Tj ET', ($this->x + $dx) * $k, ($this->h - ($this->y + .5 * $h + .3 * $this->FontSize)) * $k, $this->_escape($txt));
                if ($this->underline) {
                    $s .= ' ' . $this->_dounderline($this->x + $dx, $this->y + .5 * $h + .3 * $this->FontSize, $txt);
                }

                if ($this->ColorFlag) {
                    $s .= ' Q';
                }

                if ($link) {
                    $this->Link($this->x + $dx, $this->y + .5 * $h - .5 * $this->FontSize, $stringWidth, $this->FontSize, $link);
                }

                unset($array_txt[$ti]);
            }
            if ($s) {
                $this->_out($s);
            }

            $this->lasth = $h;
            $this->y += $h;
        }
        if ($this->ws > 0) {
            $this->ws = 0;
            $this->_out('0 Tw');
        }
    }
}

$nip = \Input::get('nip');
$jenis = \Input::get('jenis');
$subjenis = \Input::get('subjenis');
$filename = \Input::get('filename');
\Input::get('subsubjenis') == '' ? $subsubjenis = 0 : $subsubjenis = \Input::get('subsubjenis');

$files = \DB::connection('efile_2017')->table('files')
->where('nip', '=', $nip)
->where('jenis', '=', $jenis)
->where('subjenis', '=', $subjenis)
->where('subsubjenis', '=', $subsubjenis)
// ->where('status', '=', '1')
->orderby('order', 'asc')
->get();

$pdf = new exFPDF('P', 'mm', 'A4');
//$pdf->SetAutoPageBreak(true, 5);
//$pdf->SetMargins(20, 20, 20);
//$pdf->SetFont('Arial', '', '9');

$x2 = 190;
$y2 = 267;
$p1 = 180;

if($jenis != ''){ //rendyamdani 310124
    if(count($files) > 0 ){
        foreach($files as $row){
    //        $pdf->AddPage();
    //        $pdf->Image(url().'/efile/packages/upload/files/'.substr($row->nip,0,4).'/' . $row->nip . '/' . $row->filename, 10, 10, 190, 267);
    //        $qrcode = new QRcode(substr($row->filename, 0, -4), 'H'); // error level : L, M, Q, H
    //        $qrcode->displayFPDF($pdf, 180, 10, 20);

            $pdf->SetAutoPageBreak(true, 5);
            $pdf->SetMargins(20, 20, 20);
            $pdf->SetFont('Arial', '', '9');

            $fileimg = './efile/packages/upload/files/'.substr($row->nip,0,4).'/' . $row->nip . '/' . $row->filename;
            list($x1, $y1) = getimagesize($fileimg);
            if(($x1 / $y1) < ($y1 / $x1)) {
                $pdf->AddPage('P');
                $x2 = 190;
                $y2 = 267;
                $p1 = 180;
            } else {
                $pdf->AddPage('L');
                $x2 = 267;
                $y2 = 190;
                $p1 = 255;
            }

            $pdf->Image($fileimg, 10, 10, $x2,$y2);
            $qrcode = new QRcode(substr($row->filename, 0, -4), 'H'); // error level : L, M, Q, H
            $qrcode->displayFPDF($pdf, $p1, 10, 20);
        }

        $filename = explode('.', \Input::get("filename"));

        if($jenis == 9){
            $cek_dikstru = \DB::table('r_dikstru')
                ->where('id','=',$subjenis)
                ->first();

            if($cek_dikstru->iddikstru == 3){
                $nama_cetak = 'SK_PIM_'.\Input::get('nip');
            }else{
                $nama_cetak = sanitizeFilename(\Input::get('jenisdokumen')).'_'.\Input::get('nip');
            }
        }else{

            if($jenis == 6){
                $cekformat = \DB::connection('efile_2017')->table('kategori_jenis')
                    ->where('id','=',$subsubjenis)
                    ->first();
            }else{
                $cekformat = \DB::connection('efile_2017')->table('kategori_jenis')
                    ->where('id','=',$jenis)
                    ->first();

                if($cekformat->format_file == ''){
                    if($cekformat->riwayat_flag != 1){
                        $cekformat = \DB::connection('efile_2017')->table('kategori_jenis')
                            ->where('id','=',$subjenis)
                            ->first();
                    }
                }
            }

            if($cekformat->format_file != ''){
                if($cekformat->riwayat_flag == 1){
                    $nama_cetak = str_replace('IDENT', \Input::get('ident'), str_replace('NIP',\Input::get('nip'), $cekformat->format_file));
                }else{
                    $nama_cetak = str_replace('NIP', \Input::get('nip'), $cekformat->format_file);
                }
            }else{
                $nama_cetak = sanitizeFilename(\Input::get('jenisdokumen')).'_'.\Input::get('nip');

                if($cekformat->level == 3){
                    $nama_cetak = sanitizeFilename($cekformat->nama).'_'.$nama_cetak;
                }
            }
        }

        $pdf->Output($nama_cetak.'.pdf', 'I');
    }else{
        $fileimg = './efile/packages/upload/files/'.substr($nip,0,4).'/' . $nip . '/' . $filename;
        list($x1, $y1) = getimagesize($fileimg);
        if(($x1 / $y1) < ($y1 / $x1)) {
            $pdf = new exFPDF('P', 'mm', 'A4');
            $x2 = 190;
            $y2 = 267;
            $p1 = 180;
        } else {
            $pdf = new exFPDF('L', 'mm', 'A4');
            $x2 = 267;
            $y2 = 190;
            $p1 = 255;
        }

        $pdf->SetAutoPageBreak(true, 5);
        $pdf->SetMargins(20, 20, 20);
        $pdf->SetFont('Arial', '', '9');
        $pdf->AddPage();

        $pdf->Image($fileimg, 10, 10, $x2,$y2);
        $qrcode = new QRcode(substr($filename, 0, -4), 'H');
        $qrcode->displayFPDF($pdf, $p1, 10, 20);

        list($file, $type) = explode('.', \Input::get("filename"));

        $pdf->Output($file.'.pdf', 'I');
    }
}else{
    $fileimg = './efile/packages/upload/files/'.substr($nip,0,4).'/' . $nip . '/' . $filename;
    list($x1, $y1) = getimagesize($fileimg);
    if(($x1 / $y1) < ($y1 / $x1)) {
        $pdf = new exFPDF('P', 'mm', 'A4');
        $x2 = 190;
        $y2 = 267;
        $p1 = 180;
    } else {
        $pdf = new exFPDF('L', 'mm', 'A4');
        $x2 = 267;
        $y2 = 190;
        $p1 = 255;
    }

    $pdf->SetAutoPageBreak(true, 5);
    $pdf->SetMargins(20, 20, 20);
    $pdf->SetFont('Arial', '', '9');
    $pdf->AddPage();

    $pdf->Image($fileimg, 10, 10, $x2,$y2);
    $qrcode = new QRcode(substr($filename, 0, -4), 'H');
    $qrcode->displayFPDF($pdf, $p1, 10, 20);

    list($file, $type) = explode('.', \Input::get("filename"));

    $pdf->Output($file.'.pdf', 'I');
}